name: "iOS Build"

on:
  workflow_call:
    inputs:
      publish:
        required: false
        type: boolean
        description: Publish to Appcenter
    secrets:
      IOS_P12_BASE64:
        required: true
      IOS_MOBILEPROVISION_BASE64:
        required: true
      IOS_TEAM_ID:
        required: true
      IOS_CERTIFICATE_PASSWORD:
        required: true
      # APPCENTER_TOKEN_IOS:
      #   required: true

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js 14
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "yarn"

      - name: Install Node.js and NPM
        run: yarn ci

      - name: Restore buildcache
        uses: mikehardy/buildcache-action@v1
        continue-on-error: true

      # - name: Restore Pods cache
      #   uses: actions/cache@v3
      #   with:
      #     path: |
      #       ios/Pods
      #       ~/Library/Caches/CocoaPods
      #       ~/.cocoapods
      #     key: ${{ runner.os }}-pods-${{ hashFiles('ios/Podfile.lock') }}
      #     restore-keys: |
      #       ${{ runner.os }}-pods-

      # - name: Install pod dependencies
      #   run: cd ios && pod install && cd ..

      - name: Cache CocoaPods
        uses: actions/cache@v3
        with:
          path: ~/.cocoapods
          key: ${{ runner.os }}-pods-${{ hashFiles('ios/Podfile.lock') }}
          restore-keys: ${{ runner.os }}-pods


      - name: Install CocoaPods
        run: cd ios && pod install && cd ..

      - name: Decode provisioning profile
        run: echo "${{ secrets.IOS_MOBILEPROVISION_BASE64 }}" | base64 --decode > ios/Charmsta.mobileprovision
      - name: Decode certificate
        run: echo "${{ secrets.IOS_P12_BASE64 }}" | base64 --decode > ios/cert.p12
      - name: Install certificate
        run: |
          security create-keychain -p mysecretpassword build.keychain
          security import ios/cert.p12 -t agg -k ~/Library/Keychains/build.keychain -P mysecretpassword -A
          security set-key-partition-list -S apple-tool:,apple: -s -k mysecretpassword build.keychain
      - name: Build and archive app
        run: |
          xcodebuild -workspace ios/Charmsta.xcworkspace -scheme Charmsta -configuration Release archive -archivePath $PWD/build/Charmsta.xcarchive CODE_SIGN_IDENTITY="iPhone Distribution" PROVISIONING_PROFILE_SPECIFIER="Charmsta.mobileprovision"
          xcodebuild -exportArchive -archivePath $PWD/build/Charmsta.xcarchive -exportPath $PWD/build -exportOptionsPlist exportOptions.plist
      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Charmsta
          path: ios/build/Charmsta.ipa
