name: Build and Archive iOS App
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Node.js and NPM
        uses: actions/setup-node@v2.5.1
        with:
          node-version: '14.x'
      - name: Install dependencies
        run: npm install
      - name: Cache CocoaPods
        uses: actions/cache@v2
        with:
          path: ~/.cocoapods
          key: ${{ runner.os }}-pods-${{ hashFiles('ios/Podfile.lock') }}
          restore-keys: ${{ runner.os }}-pods
      - name: Install CocoaPods
        run: cd ios && pod install
      - name: Decode provisioning profile
        run: echo "${{ secrets.PROVISIONING_PROFILE }}" | base64 --decode > ios/MyApp.mobileprovision
      - name: Decode certificate
        run: echo "${{ secrets.CODE_SIGNING_CERTIFICATE }}" | base64 --decode > ios/cert.p12
      - name: Install certificate
        run: |
          security create-keychain -p mysecretpassword build.keychain
          security import ios/cert.p12 -t agg -k ~/Library/Keychains/build.keychain -P mysecretpassword -A
          security set-key-partition-list -S apple-tool:,apple: -s -k mysecretpassword build.keychain
      - name: Build and archive app
        run: |
          xcodebuild -workspace ios/MyApp.xcworkspace -scheme MyApp -configuration Release archive -archivePath $PWD/build/MyApp.xcarchive CODE_SIGN_IDENTITY="iPhone Distribution" PROVISIONING_PROFILE_SPECIFIER="MyApp.mobileprovision"
          xcodebuild -exportArchive -archivePath $PWD/build/MyApp.xcarchive -exportPath $PWD/build -exportOptionsPlist exportOptions.plist
      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: MyApp
          path: ios/build/MyApp.ipa
